sudo: required
services:
  - docker
  
before_install:
  - docker build -t react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run react-test npm test -- --coverage

after_success:
  - docker build -t emunn/multi-client ./client
  - docker build -t emunn/multi-nginx ./nginx
  - docker build -t emunn/multi-server ./server
  - docker build -t emunn/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push emunn/multi-client
  - docker push emunn/multi-nginx
  - docker push emunn/multi-server
  - docker push emunn/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-west-2
  app: multi-docker
  env: multi-docker-env
  bucket_name: elasticbeanstalk-us-west-2-951895215485
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
